discord:
    bot_token: Njk1NjYyODk4OTE5NTA2MDIw.XodhQg.DTx1rAKNGk4-ATUbSwzyhtEuGT0
    bot_id: 695662898919506020
    bot_secret: veKJms-YcoLHiYQ9-cgbSlKDJuDPXoKW
    admin_id: 170939974227591168
    invite_link: https://discordapp.com/api/oauth2/authorize?client_id=695662898919506020&permissions=1345711302&scope=bot
    website_url: http://localhost/guilds
    ksoft_token: 0GYwSKasRHwNCIVuKzgSFeFiuVgDtU4e

postgres:
    host: localhost
    port: 5432
    database: kittybot
    user: kittybot
    password: 436cewc54w

lavalink_nodes:
    lavalink_1:
        host: localhost
        port: 2333
        password: n980z8v56
